### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by graham-haworth** [adobe/storefront-product-listing-page#3]
### Expected Behaviour
npm install runs successfully
 
### Actual Behaviour
npm install fails

npm i
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://artifactory.corp.adobe.com/artifactory/api/npm/npm-adobe-release/webpack-bundle-analyzer/-/webpack-bundle-analyzer-4.9.1.tgz failed, reason: unable to get local issuer certificate

npm config set strict-ssl false

npm i
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://adobe.trust-adobe.console.banyanops.com/v2/auth?client_id=ePcIQuesF41DxqDK3gTuUw&nonce=LVfLrA2f25xoqKD7x1kKq&redirect_uri=https%3A%2F%2Fartifactory.corp.adobe.com%2Fbnn_trust_cb&response_type=code&scope=openid+profile+email&state=tUQhQR41TgWPsVMwvquIhA

### Reproduce Scenario (including but not limited to)
clone this repository
npm i 

#### Steps to Reproduce
clone this repository
npm i

**Comment by aniham** [comment]
@graham-haworth thank you for letting us know! should be fixed now! please let us know if you're still running into issues!!

**Comment by tapantechno2007** [comment]
I have experienced the same issue installing it today. When switched to VPN I noticed there are no issues.

**Comment by aniham** [comment]
@tapantechno2007 this issue should be resolved. please try with a clean copy of the repo!

**Comment by gabriel3iri** [comment]
it's still happening for me

**Comment by danielcpi** [comment]
I have experienced the same issue installing it today.

**Comment by kathleentynan** [comment]
This is resolved by deleting package-lock.json, node modules and re-running `npm i`.

Alternatively, we have pushed changes to the main repo that should resolve this.
